//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscrepancyDescriptions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscrepancyDescriptions()
        {
            this.TraceDiscrepancies = new HashSet<TraceDiscrepancies>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraceDiscrepancies> TraceDiscrepancies { get; set; }
    }
}
