//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDTS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinancialdocumenttrackersystemEntities : DbContext
    {
        public FinancialdocumenttrackersystemEntities()
            : base("name=FinancialdocumenttrackersystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressStateProvinces> AddressStateProvinces { get; set; }
        public virtual DbSet<AddressTownCities> AddressTownCities { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<DiscrepancyDescriptions> DiscrepancyDescriptions { get; set; }
        public virtual DbSet<DocumentAttachments> DocumentAttachments { get; set; }
        public virtual DbSet<RequestTypes> RequestTypes { get; set; }
        public virtual DbSet<TraceDiscrepancies> TraceDiscrepancies { get; set; }
        public virtual DbSet<TraceDocuments> TraceDocuments { get; set; }
        public virtual DbSet<TraceTransactions> TraceTransactions { get; set; }
        public virtual DbSet<UserClaims> UserClaims { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
