//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraceTransactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TraceTransactions()
        {
            this.TraceDiscrepancies = new HashSet<TraceDiscrepancies>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TraceDocumentId { get; set; }
        public Nullable<System.DateTime> TraceDate { get; set; }
        public string ReceivingPersonnelId { get; set; }
        public string LiasonId { get; set; }
        public Nullable<int> ReceivingDepartmentId { get; set; }
        public string CreatedBy { get; set; }
        public bool isReceived { get; set; }
        public bool isTransmit { get; set; }
    
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraceDiscrepancies> TraceDiscrepancies { get; set; }
        public virtual TraceDocuments TraceDocuments { get; set; }
        public virtual Users Liasons { get; set; }
        public virtual Users ReceivingPersonnels { get; set; }
        public virtual Users CreatedByUsers { get; set; }
    }
}
