//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraceDocuments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TraceDocuments()
        {
            this.TraceTransactions = new HashSet<TraceTransactions>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Barcode { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> RequestTypeId { get; set; }
        public string CreatedById { get; set; }
        public Nullable<int> DocumentAttachmentId { get; set; }
        public byte[] Upload { get; set; }
        public string LiasonId { get; set; }
        public Nullable<int> RequestingDepartmentId { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual DocumentAttachments DocumentAttachments { get; set; }
        public virtual RequestTypes RequestTypes { get; set; }
        public virtual Users CreatedBy { get; set; }
        public virtual Users Liasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraceTransactions> TraceTransactions { get; set; }
    }
}
