//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraceDiscrepancies
    {
        public int Id { get; set; }
        public Nullable<int> TraceTransactionId { get; set; }
        public Nullable<int> DocumentAttachmentId { get; set; }
        public Nullable<int> DiscrepancyDescriptionId { get; set; }
        public string DiscrepancyNotes { get; set; }
    
        public virtual DiscrepancyDescriptions DiscrepancyDescriptions { get; set; }
        public virtual DocumentAttachments DocumentAttachments { get; set; }
        public virtual TraceTransactions TraceTransactions { get; set; }
    }
}
